// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Test NWC connection and get balance
Future<BigInt> testNwcConnection({required String connectionString}) =>
    RustLib.instance.api.crateApiTestNwcConnection(connectionString: connectionString);

/// Execute Lightning payment
Future<String> payLightningInvoice({
  required String connectionString,
  required String lightningAddress,
  required BigInt amountSats,
  String? comment,
}) => RustLib.instance.api.crateApiPayLightningInvoice(
  connectionString: connectionString,
  lightningAddress: lightningAddress,
  amountSats: amountSats,
  comment: comment,
);
